spring.application.name=kunce-self-love-bombs
spring.datasource.url=jdbc:mysql://localhost:3306/unit_2_project_becca_k
spring.datasource.username=root
spring.datasource.password=IAMROOT369!!
spring.jpa.hibernate.ddl-auto=update